### PR TITLE
Fix cargo module load when executable is not present.

### LINKED ISSUE #17: "auto" task not working when cargo not installed
There seems to be an issue with the `cargo.lua` module.

Basically, loading the module requires `cargo` being installed:
- the definition of `cargo.tasks` [calls](https://github.com/Shatur/neovim-tasks/blob/f42b164499b6e833ac6b94993abc215fc4a0db17/lua/tasks/module/cargo.lua#L170) `get_cargo_subcommands()`;
- it, in turn, [creates a new `Job`](https://github.com/Shatur/neovim-tasks/blob/f42b164499b6e833ac6b94993abc215fc4a0db17/lua/tasks/module/cargo.lua#L83-L86) running `cargo`;
- `Job:new(...)` from plenary.nvim [checks](https://github.com/nvim-lua/plenary.nvim/blob/366b0837486f60ae0e7550c15de8ff66d057c4cd/lua/plenary/job.lua#L105-L108) whether the command is executable and fails if it's not.

This is a problem when using `auto` as the target module, since this will [try to load every module](https://github.com/Shatur/neovim-tasks/blob/f42b164499b6e833ac6b94993abc215fc4a0db17/lua/tasks/utils.lua#L81-L86) to call the appropriate `condition()`, even when `cargo` is not installed.

Personally, I would check this in `get_cargo_subcommands` as

```lua
local cmd = 'cargo'
local ok, is_exe = pcall(vim.fn.executable, cmd)
if ok and 1 ~= is_exe then
  utils.notify('Unable to find "cargo" executable', vim.log.levels.WARN)
  return {}
end

local job = Job:new({
  command = cmd,
  args = { '--list' },
  enabled_recording = true,
})
job:sync()

if job.code ~= 0 or job.signal ~= 0 then
  utils.notify('Unable to get list of available cargo subcommands', vim.log.levels.WARN)
  return {}
end
```

Hope this helps!

### PR DESCRIPTION
**Pull request by undyamon**
Closes #17

### CODE REVIEW

File: lua/tasks/module/cargo.lua [hunk 1]
```diff
@@ -78,8 +78,15 @@ end
 
 ---@return table: List of functions for each cargo subcommand that return a task table.
 local function get_cargo_subcommands()
+  local cmd = 'cargo'
   local cargo_subcommands = {}
 
+  local ok, is_exe = pcall(vim.fn.executable, cmd)
```
Comment (Shatur) [inline lua/tasks/module/cargo.lua:84]: Maybe put `Job:new` here to avoid checking if it's an executable twice?

**Review by Shatur — CHANGES_REQUESTED** [review]

File: lua/tasks/module/cargo.lua (hunk 1 above)
Comment (undyamon) [reply lua/tasks/module/cargo.lua:84]: You mean something like this?

```lua
  local ok, job = pcall(Job.new, Job, {
    command = 'cargo',
    args = { '--list' },
    enabled_recording = true,
  })
  if not ok then
    utils.notify(job, vim.log.levels.WARN)
    return {}
  end
  job:sync()

  if job.code ~= 0 or job.signal ~= 0 then
    utils.notify('Unable to get list of available cargo subcommands', vim.log.levels.WARN)
    return {}
  end
```

Comment (Shatur) [reply lua/tasks/module/cargo.lua:84]: Yep!

Comment (undyamon) [reply lua/tasks/module/cargo.lua]: I pushed so I could test the config in nixos. Hold on a sec.

Comment (undyamon) [reply lua/tasks/module/cargo.lua]:
```lua
utils.notify(job, vim.log.levels.WARN)
```

This line dumps the stack trace as a warning the first time one uses `auto` (and it realizes `cargo` is not available). It is slightly annoying because it causes the classic `Press ENTER or type command to continue`.

Do you have a better idea on how to handle this? Sometimes it could be useful to get the warning so I don't think we should discard it.

Comment (Shatur) [reply lua/tasks/module/cargo.lua]: I think it's fine if user uses `auto` in a repo with `Cargo.toml`? But instead of stacktrace I would write something like 'unable to execute "cargo"'.

**Review by Shatur — APPROVED** [review]
